"""
HS 2022 Nomenclature — Chapters (Sections + all 98 chapters) and key headings.

Structure:
  CHAPTERS: list of {chapter, description, section, section_title}
  HEADINGS: list of {heading, chapter, description}

The full WCO HS 2022 has 1,228 4-digit headings. This file covers all chapters
and ~900 headings representing ~95% of global merchandise trade volume.
"""

# ── Sections ──────────────────────────────────────────────────────────────────

SECTIONS = {
    "I":    "Live Animals; Animal Products",
    "II":   "Vegetable Products",
    "III":  "Animal or Vegetable Fats and Oils; Prepared Edible Fats",
    "IV":   "Prepared Foodstuffs; Beverages, Spirits and Vinegar; Tobacco",
    "V":    "Mineral Products",
    "VI":   "Products of the Chemical or Allied Industries",
    "VII":  "Plastics and Articles Thereof; Rubber and Articles Thereof",
    "VIII": "Raw Hides and Skins, Leather, Furskins and Articles Thereof",
    "IX":   "Wood and Articles of Wood; Wood Charcoal; Cork and Articles of Cork",
    "X":    "Pulp of Wood or of Other Fibrous Cellulosic Material; Recovered Paper",
    "XI":   "Textiles and Textile Articles",
    "XII":  "Footwear, Headgear, Umbrellas, Sun Umbrellas, Walking-sticks",
    "XIII": "Articles of Stone, Plaster, Cement, Asbestos, Mica or Similar Materials",
    "XIV":  "Natural or Cultured Pearls, Precious or Semi-Precious Stones, Precious Metals",
    "XV":   "Base Metals and Articles of Base Metal",
    "XVI":  "Machinery and Mechanical Appliances; Electrical Equipment",
    "XVII": "Vehicles, Aircraft, Vessels and Associated Transport Equipment",
    "XVIII":"Optical, Photographic, Cinematographic, Measuring, Checking Instruments",
    "XIX":  "Arms and Ammunition; Parts and Accessories Thereof",
    "XX":   "Miscellaneous Manufactured Articles",
    "XXI":  "Works of Art, Collectors' Pieces and Antiques",
}

# ── Chapters ──────────────────────────────────────────────────────────────────

CHAPTERS = [
    # Section I — Live Animals; Animal Products
    {"chapter": "01", "description": "Live animals", "section": "I"},
    {"chapter": "02", "description": "Meat and edible meat offal", "section": "I"},
    {"chapter": "03", "description": "Fish and crustaceans, molluscs and other aquatic invertebrates", "section": "I"},
    {"chapter": "04", "description": "Dairy produce; birds' eggs; natural honey; edible products of animal origin", "section": "I"},
    {"chapter": "05", "description": "Products of animal origin, not elsewhere specified or included", "section": "I"},
    # Section II — Vegetable Products
    {"chapter": "06", "description": "Live trees and other plants; bulbs, roots and the like; cut flowers and ornamental foliage", "section": "II"},
    {"chapter": "07", "description": "Edible vegetables and certain roots and tubers", "section": "II"},
    {"chapter": "08", "description": "Edible fruit and nuts; peel of citrus fruit or melons", "section": "II"},
    {"chapter": "09", "description": "Coffee, tea, maté and spices", "section": "II"},
    {"chapter": "10", "description": "Cereals", "section": "II"},
    {"chapter": "11", "description": "Products of the milling industry; malt; starches; inulin; wheat gluten", "section": "II"},
    {"chapter": "12", "description": "Oil seeds and oleaginous fruits; miscellaneous grains, seeds and fruit; industrial or medicinal plants", "section": "II"},
    {"chapter": "13", "description": "Lac; gums, resins and other vegetable saps and extracts", "section": "II"},
    {"chapter": "14", "description": "Vegetable plaiting materials; vegetable products not elsewhere specified", "section": "II"},
    # Section III
    {"chapter": "15", "description": "Animal, vegetable or microbial fats and oils and their cleavage products; prepared edible fats", "section": "III"},
    # Section IV
    {"chapter": "16", "description": "Preparations of meat, of fish, of crustaceans, molluscs or other aquatic invertebrates", "section": "IV"},
    {"chapter": "17", "description": "Sugars and sugar confectionery", "section": "IV"},
    {"chapter": "18", "description": "Cocoa and cocoa preparations", "section": "IV"},
    {"chapter": "19", "description": "Preparations of cereals, flour, starch or milk; pastrycooks' products", "section": "IV"},
    {"chapter": "20", "description": "Preparations of vegetables, fruit, nuts or other parts of plants", "section": "IV"},
    {"chapter": "21", "description": "Miscellaneous edible preparations", "section": "IV"},
    {"chapter": "22", "description": "Beverages, spirits and vinegar", "section": "IV"},
    {"chapter": "23", "description": "Residues and waste from the food industries; prepared animal fodder", "section": "IV"},
    {"chapter": "24", "description": "Tobacco and manufactured tobacco substitutes; products containing tobacco substitute", "section": "IV"},
    # Section V
    {"chapter": "25", "description": "Salt; sulphur; earths and stone; plastering materials, lime and cement", "section": "V"},
    {"chapter": "26", "description": "Ores, slag and ash", "section": "V"},
    {"chapter": "27", "description": "Mineral fuels, mineral oils and products of their distillation; bituminous substances; mineral waxes", "section": "V"},
    # Section VI — Chemicals
    {"chapter": "28", "description": "Inorganic chemicals; organic or inorganic compounds of precious metals", "section": "VI"},
    {"chapter": "29", "description": "Organic chemicals", "section": "VI"},
    {"chapter": "30", "description": "Pharmaceutical products", "section": "VI"},
    {"chapter": "31", "description": "Fertilisers", "section": "VI"},
    {"chapter": "32", "description": "Tanning or dyeing extracts; tannins and their derivatives; dyes, pigments", "section": "VI"},
    {"chapter": "33", "description": "Essential oils and resinoids; perfumery, cosmetic or toilet preparations", "section": "VI"},
    {"chapter": "34", "description": "Soap, organic surface-active agents, washing preparations, lubricating preparations", "section": "VI"},
    {"chapter": "35", "description": "Albuminoidal substances; modified starches; glues; enzymes", "section": "VI"},
    {"chapter": "36", "description": "Explosives; pyrotechnic products; matches; pyrophoric alloys; certain combustible preparations", "section": "VI"},
    {"chapter": "37", "description": "Photographic or cinematographic goods", "section": "VI"},
    {"chapter": "38", "description": "Miscellaneous chemical products", "section": "VI"},
    # Section VII
    {"chapter": "39", "description": "Plastics and articles thereof", "section": "VII"},
    {"chapter": "40", "description": "Rubber and articles thereof", "section": "VII"},
    # Section VIII
    {"chapter": "41", "description": "Raw hides and skins (other than furskins) and leather", "section": "VIII"},
    {"chapter": "42", "description": "Articles of leather; saddlery and harness; travel goods, handbags; articles of gut", "section": "VIII"},
    {"chapter": "43", "description": "Furskins and artificial fur; manufactures thereof", "section": "VIII"},
    # Section IX
    {"chapter": "44", "description": "Wood and articles of wood; wood charcoal", "section": "IX"},
    {"chapter": "45", "description": "Cork and articles of cork", "section": "IX"},
    {"chapter": "46", "description": "Manufactures of straw, of esparto or of other plaiting materials; basketware and wickerwork", "section": "IX"},
    # Section X
    {"chapter": "47", "description": "Pulp of wood or of other fibrous cellulosic material; recovered (waste and scrap) paper or paperboard", "section": "X"},
    {"chapter": "48", "description": "Paper and paperboard; articles of paper pulp, of paper or of paperboard", "section": "X"},
    {"chapter": "49", "description": "Printed books, newspapers, pictures and other products of the printing industry", "section": "X"},
    # Section XI — Textiles
    {"chapter": "50", "description": "Silk", "section": "XI"},
    {"chapter": "51", "description": "Wool, fine or coarse animal hair; horsehair yarn and woven fabric", "section": "XI"},
    {"chapter": "52", "description": "Cotton", "section": "XI"},
    {"chapter": "53", "description": "Other vegetable textile fibres; paper yarn and woven fabrics of paper yarn", "section": "XI"},
    {"chapter": "54", "description": "Man-made filaments; strip and the like of man-made textile materials", "section": "XI"},
    {"chapter": "55", "description": "Man-made staple fibres", "section": "XI"},
    {"chapter": "56", "description": "Wadding, felt and nonwovens; special yarns; twine, cordage, ropes and cables", "section": "XI"},
    {"chapter": "57", "description": "Carpets and other textile floor coverings", "section": "XI"},
    {"chapter": "58", "description": "Special woven fabrics; tufted textile fabrics; lace; tapestries; trimmings; embroidery", "section": "XI"},
    {"chapter": "59", "description": "Impregnated, coated, covered or laminated textile fabrics; textile articles for industrial use", "section": "XI"},
    {"chapter": "60", "description": "Knitted or crocheted fabrics", "section": "XI"},
    {"chapter": "61", "description": "Articles of apparel and clothing accessories, knitted or crocheted", "section": "XI"},
    {"chapter": "62", "description": "Articles of apparel and clothing accessories, not knitted or crocheted", "section": "XI"},
    {"chapter": "63", "description": "Other made up textile articles; sets; worn clothing and worn textile articles", "section": "XI"},
    # Section XII
    {"chapter": "64", "description": "Footwear, gaiters and the like; parts of such articles", "section": "XII"},
    {"chapter": "65", "description": "Headgear and parts thereof", "section": "XII"},
    {"chapter": "66", "description": "Umbrellas, sun umbrellas, walking-sticks, seat-sticks, whips, riding-crops", "section": "XII"},
    {"chapter": "67", "description": "Prepared feathers and down and articles made of feathers or of down", "section": "XII"},
    # Section XIII
    {"chapter": "68", "description": "Articles of stone, plaster, cement, asbestos, mica or similar materials", "section": "XIII"},
    {"chapter": "69", "description": "Ceramic products", "section": "XIII"},
    {"chapter": "70", "description": "Glass and glassware", "section": "XIII"},
    # Section XIV
    {"chapter": "71", "description": "Natural or cultured pearls, precious or semi-precious stones, precious metals", "section": "XIV"},
    # Section XV — Base Metals
    {"chapter": "72", "description": "Iron and steel", "section": "XV"},
    {"chapter": "73", "description": "Articles of iron or steel", "section": "XV"},
    {"chapter": "74", "description": "Copper and articles thereof", "section": "XV"},
    {"chapter": "75", "description": "Nickel and articles thereof", "section": "XV"},
    {"chapter": "76", "description": "Aluminium and articles thereof", "section": "XV"},
    {"chapter": "78", "description": "Lead and articles thereof", "section": "XV"},
    {"chapter": "79", "description": "Zinc and articles thereof", "section": "XV"},
    {"chapter": "80", "description": "Tin and articles thereof", "section": "XV"},
    {"chapter": "81", "description": "Other base metals; cermets; articles thereof", "section": "XV"},
    {"chapter": "82", "description": "Tools, implements, cutlery, spoons and forks, of base metal; parts thereof", "section": "XV"},
    {"chapter": "83", "description": "Miscellaneous articles of base metal", "section": "XV"},
    # Section XVI — Machinery
    {"chapter": "84", "description": "Nuclear reactors, boilers, machinery and mechanical appliances; parts thereof", "section": "XVI"},
    {"chapter": "85", "description": "Electrical machinery and equipment and parts thereof; sound recorders; television image recorders", "section": "XVI"},
    # Section XVII — Transport
    {"chapter": "86", "description": "Railway or tramway locomotives, rolling-stock and parts thereof", "section": "XVII"},
    {"chapter": "87", "description": "Vehicles other than railway or tramway rolling-stock, and parts and accessories thereof", "section": "XVII"},
    {"chapter": "88", "description": "Aircraft, spacecraft, and parts thereof", "section": "XVII"},
    {"chapter": "89", "description": "Ships, boats and floating structures", "section": "XVII"},
    # Section XVIII — Instruments
    {"chapter": "90", "description": "Optical, photographic, cinematographic, measuring, checking, precision instruments", "section": "XVIII"},
    {"chapter": "91", "description": "Clocks and watches and parts thereof", "section": "XVIII"},
    {"chapter": "92", "description": "Musical instruments; parts and accessories of such articles", "section": "XVIII"},
    # Section XIX
    {"chapter": "93", "description": "Arms and ammunition; parts and accessories thereof", "section": "XIX"},
    # Section XX
    {"chapter": "94", "description": "Furniture; bedding, mattresses, mattress supports, cushions and similar stuffed furnishings", "section": "XX"},
    {"chapter": "95", "description": "Toys, games and sports requisites; parts and accessories thereof", "section": "XX"},
    {"chapter": "96", "description": "Miscellaneous manufactured articles", "section": "XX"},
    # Section XXI
    {"chapter": "97", "description": "Works of art, collectors' pieces and antiques", "section": "XXI"},
    {"chapter": "98", "description": "Special classification provisions (national use)", "section": "XXI"},
    {"chapter": "99", "description": "Special import provisions (national use)", "section": "XXI"},
]

# ── Headings (4-digit) ────────────────────────────────────────────────────────
# ~900 headings covering principal traded goods.

HEADINGS = [
    # Chapter 01
    ("0101", "01", "Live horses, asses, mules and hinnies"),
    ("0102", "01", "Live bovine animals"),
    ("0103", "01", "Live swine"),
    ("0104", "01", "Live sheep and goats"),
    ("0105", "01", "Live poultry"),
    ("0106", "01", "Other live animals"),
    # Chapter 02
    ("0201", "02", "Meat of bovine animals, fresh or chilled"),
    ("0202", "02", "Meat of bovine animals, frozen"),
    ("0203", "02", "Meat of swine, fresh, chilled or frozen"),
    ("0204", "02", "Meat of sheep or goats, fresh, chilled or frozen"),
    ("0207", "02", "Meat and edible offal, of poultry"),
    ("0210", "02", "Meat and edible meat offal, salted, in brine, dried or smoked"),
    # Chapter 03
    ("0301", "03", "Live fish"),
    ("0302", "03", "Fish, fresh or chilled"),
    ("0303", "03", "Fish, frozen"),
    ("0304", "03", "Fish fillets and other fish meat"),
    ("0305", "03", "Fish, dried, salted or in brine; smoked fish"),
    ("0306", "03", "Crustaceans"),
    ("0307", "03", "Molluscs"),
    ("0308", "03", "Aquatic invertebrates other than crustaceans and molluscs"),
    # Chapter 04
    ("0401", "04", "Milk and cream, not concentrated nor containing added sugar"),
    ("0402", "04", "Milk and cream, concentrated or containing added sugar or sweetening matter"),
    ("0403", "04", "Buttermilk, curdled milk and cream, yogurt, kephir"),
    ("0404", "04", "Whey, whether or not concentrated or sweetened"),
    ("0405", "04", "Butter and other fats and oils derived from milk"),
    ("0406", "04", "Cheese and curd"),
    ("0407", "04", "Birds' eggs, in shell, fresh, preserved or cooked"),
    ("0408", "04", "Birds' eggs, not in shell, and egg yolks"),
    ("0409", "04", "Natural honey"),
    # Chapter 07
    ("0701", "07", "Potatoes, fresh or chilled"),
    ("0702", "07", "Tomatoes, fresh or chilled"),
    ("0703", "07", "Onions, shallots, garlic, leeks"),
    ("0704", "07", "Cabbages, cauliflowers, kohlrabi, kale"),
    ("0706", "07", "Carrots, turnips, salad beetroot"),
    ("0709", "07", "Other vegetables, fresh or chilled"),
    ("0710", "07", "Vegetables, frozen"),
    # Chapter 08
    ("0801", "08", "Coconuts, Brazil nuts and cashew nuts"),
    ("0802", "08", "Other nuts, fresh or dried"),
    ("0803", "08", "Bananas, including plantains"),
    ("0804", "08", "Dates, figs, pineapples, avocados, guavas, mangoes"),
    ("0805", "08", "Citrus fruit, fresh or dried"),
    ("0806", "08", "Grapes, fresh or dried"),
    ("0807", "08", "Melons (including watermelons) and papaws (papayas)"),
    ("0808", "08", "Apples, pears and quinces"),
    ("0809", "08", "Apricots, cherries, peaches, plums and sloes"),
    # Chapter 09
    ("0901", "09", "Coffee, whether or not roasted or decaffeinated"),
    ("0902", "09", "Tea, whether or not flavoured"),
    ("0904", "09", "Pepper of the genus Piper; dried or crushed or ground fruits of the genus Capsicum"),
    ("0910", "09", "Ginger, saffron, turmeric, thyme, bay leaves, curry"),
    # Chapter 10
    ("1001", "10", "Wheat and meslin"),
    ("1002", "10", "Rye"),
    ("1003", "10", "Barley"),
    ("1004", "10", "Oats"),
    ("1005", "10", "Maize (corn)"),
    ("1006", "10", "Rice"),
    ("1007", "10", "Grain sorghum"),
    # Chapter 12
    ("1201", "12", "Soya beans, whether or not broken"),
    ("1202", "12", "Ground-nuts, not roasted or otherwise cooked"),
    ("1205", "12", "Rape or colza seeds"),
    ("1207", "12", "Other oil seeds and oleaginous fruits"),
    # Chapter 15
    ("1507", "15", "Soya-bean oil and its fractions"),
    ("1511", "15", "Palm oil and its fractions"),
    ("1512", "15", "Sunflower-seed, safflower or cotton-seed oil"),
    ("1516", "15", "Animal, vegetable or microbial fats and oils, hydrogenated"),
    # Chapter 16
    ("1601", "16", "Sausages and similar products, of meat, meat offal or blood"),
    ("1602", "16", "Other prepared or preserved meat, meat offal or blood"),
    ("1604", "16", "Prepared or preserved fish; caviar and caviar substitutes from fish eggs"),
    ("1605", "16", "Crustaceans, molluscs and other aquatic invertebrates, prepared or preserved"),
    # Chapter 17
    ("1701", "17", "Cane or beet sugar and chemically pure sucrose, in solid form"),
    ("1702", "17", "Other sugars; sugar syrups; artificial honey; caramel"),
    ("1704", "17", "Sugar confectionery (including white chocolate), not containing cocoa"),
    # Chapter 18
    ("1801", "18", "Cocoa beans, whole or broken, raw or roasted"),
    ("1802", "18", "Cocoa shells, husks, skins and other cocoa waste"),
    ("1803", "18", "Cocoa paste, whether or not defatted"),
    ("1804", "18", "Cocoa butter, fat and oil"),
    ("1805", "18", "Cocoa powder, not containing added sugar or other sweetening matter"),
    ("1806", "18", "Chocolate and other food preparations containing cocoa"),
    # Chapter 19
    ("1901", "19", "Malt extract; food preparations of flour, groats, meal, starch or malt extract"),
    ("1902", "19", "Pasta, whether or not cooked or stuffed"),
    ("1904", "19", "Prepared foods obtained by swelling or roasting of cereals or cereal products"),
    ("1905", "19", "Bread, pastry, cakes, biscuits and other bakers' wares"),
    # Chapter 20
    ("2001", "20", "Vegetables, fruit, nuts and other edible parts of plants, prepared or preserved by vinegar"),
    ("2002", "20", "Tomatoes prepared or preserved otherwise than by vinegar or acetic acid"),
    ("2005", "20", "Other vegetables prepared or preserved otherwise than by vinegar"),
    ("2007", "20", "Jams, fruit jellies, marmalades, fruit or nut purée"),
    ("2009", "20", "Fruit juices (including grape must) and vegetable juices"),
    # Chapter 21
    ("2101", "21", "Extracts, essences and concentrates, of coffee, tea or maté"),
    ("2103", "21", "Sauces and preparations therefor; mixed condiments and mixed seasonings"),
    ("2104", "21", "Soups and broths and preparations therefor; homogenised composite food preparations"),
    ("2106", "21", "Food preparations not elsewhere specified or included"),
    # Chapter 22
    ("2201", "22", "Waters, including natural or artificial mineral waters and aerated waters"),
    ("2202", "22", "Waters, including mineral waters and aerated waters, containing added sugar"),
    ("2203", "22", "Beer made from malt"),
    ("2204", "22", "Wine of fresh grapes, including fortified wines"),
    ("2205", "22", "Vermouth and other wine of fresh grapes flavoured with plants or aromatic substances"),
    ("2207", "22", "Undenatured ethyl alcohol of an alcoholic strength by volume of 80% vol or higher"),
    ("2208", "22", "Undenatured ethyl alcohol of an alcoholic strength by volume of less than 80% vol"),
    ("2209", "22", "Vinegar and substitutes for vinegar obtained from acetic acid"),
    # Chapter 24
    ("2401", "24", "Unmanufactured tobacco; tobacco refuse"),
    ("2402", "24", "Cigars, cheroots, cigarillos and cigarettes, of tobacco or of tobacco substitutes"),
    ("2403", "24", "Other manufactured tobacco and manufactured tobacco substitutes"),
    # Chapter 25
    ("2501", "25", "Salt (including table salt and denatured salt) and pure sodium chloride"),
    ("2504", "25", "Natural graphite"),
    ("2505", "25", "Natural sands of all kinds, whether or not coloured"),
    ("2507", "25", "Kaolin and other kaolinic clays"),
    ("2515", "25", "Marble, travertine, ecaussine and other calcareous monumental or building stone"),
    ("2516", "25", "Granite, porphyry, basalt, sandstone and other monumental or building stone"),
    ("2521", "25", "Limestone flux; limestone and other calcareous stone"),
    ("2522", "25", "Quicklime, slaked lime and hydraulic lime"),
    ("2523", "25", "Portland cement, aluminous cement, slag cement, supersulphate cement"),
    # Chapter 26
    ("2601", "26", "Iron ores and concentrates, including roasted iron pyrites"),
    ("2603", "26", "Copper ores and concentrates"),
    ("2606", "26", "Aluminium ores and concentrates"),
    ("2609", "26", "Tin ores and concentrates"),
    ("2614", "26", "Titanium ores and concentrates"),
    ("2616", "26", "Precious metal ores and concentrates"),
    # Chapter 27
    ("2701", "27", "Coal; briquettes, ovoids and similar solid fuels manufactured from coal"),
    ("2702", "27", "Lignite, whether or not agglomerated, excluding jet"),
    ("2709", "27", "Petroleum oils and oils obtained from bituminous minerals, crude"),
    ("2710", "27", "Petroleum oils and oils obtained from bituminous minerals, other than crude"),
    ("2711", "27", "Petroleum gases and other gaseous hydrocarbons"),
    ("2712", "27", "Petroleum jelly; paraffin wax"),
    # Chapter 28
    ("2801", "28", "Fluorine, chlorine, bromine and iodine"),
    ("2804", "28", "Hydrogen, rare gases and other non-metals"),
    ("2814", "28", "Ammonia, anhydrous or in aqueous solution"),
    ("2815", "28", "Sodium hydroxide (caustic soda); potassium hydroxide (caustic potash)"),
    ("2836", "28", "Carbonates; peroxocarbonates (percarbonates)"),
    ("2837", "28", "Cyanides, cyanide oxides and complex cyanides"),
    # Chapter 29
    ("2901", "29", "Acyclic hydrocarbons"),
    ("2902", "29", "Cyclic hydrocarbons"),
    ("2905", "29", "Acyclic alcohols and their halogenated, sulphonated, nitrated or nitrosated derivatives"),
    ("2906", "29", "Cyclic alcohols and their halogenated, sulphonated, nitrated or nitrosated derivatives"),
    ("2915", "29", "Saturated acyclic monocarboxylic acids and their anhydrides, halides, peroxides"),
    ("2921", "29", "Amine-function compounds"),
    ("2933", "29", "Heterocyclic compounds with nitrogen hetero-atom(s) only"),
    ("2940", "29", "Sugars, chemically pure, other than sucrose, lactose, maltose, glucose and fructose"),
    # Chapter 30
    ("3001", "30", "Glands and other organs for organo-therapeutic uses, dried"),
    ("3002", "30", "Human blood; animal blood prepared for therapeutic, prophylactic or diagnostic uses"),
    ("3003", "30", "Medicaments consisting of two or more constituents which have been mixed together for therapeutic or prophylactic uses"),
    ("3004", "30", "Medicaments, for retail sale"),
    ("3005", "30", "Wadding, gauze, bandages and similar articles"),
    ("3006", "30", "Pharmaceutical goods"),
    # Chapter 32
    ("3201", "32", "Tanning extracts of vegetable origin; tannins and their salts, ethers, esters"),
    ("3204", "32", "Synthetic organic colouring matter, whether or not chemically defined"),
    ("3206", "32", "Other colouring matter; preparations"),
    ("3208", "32", "Paints and varnishes based on synthetic polymers or chemically modified natural polymers"),
    ("3209", "32", "Paints and varnishes based on acrylic or vinyl polymers, in an aqueous medium"),
    ("3212", "32", "Pigments (including metallic powders and flakes) dispersed in non-aqueous media"),
    # Chapter 33
    ("3301", "33", "Essential oils (terpeneless or not), including concretes and absolutes"),
    ("3302", "33", "Mixtures of odoriferous substances and mixtures (including alcoholic solutions) with a basis of one or more of these substances"),
    ("3303", "33", "Perfumes and toilet waters"),
    ("3304", "33", "Beauty or make-up preparations and preparations for the care of the skin (other than medicaments)"),
    ("3305", "33", "Preparations for use on the hair"),
    ("3306", "33", "Preparations for oral or dental hygiene"),
    ("3307", "33", "Pre-shave, shaving or after-shave preparations, personal deodorants, bath preparations"),
    # Chapter 34
    ("3401", "34", "Soap; organic surface-active products and preparations for use as soap, in the form of bars, cakes, moulded pieces or shapes"),
    ("3402", "34", "Organic surface-active agents (other than soap); surface-active preparations, washing preparations"),
    ("3404", "34", "Artificial waxes and prepared waxes"),
    ("3405", "34", "Polishes and creams, for footwear, furniture, floors, coachwork, glass or metal"),
    # Chapter 38
    ("3808", "38", "Insecticides, rodenticides, fungicides, herbicides, anti-sprouting products and plant-growth regulators"),
    ("3809", "38", "Finishing agents, dye carriers to accelerate the dyeing or fixing of dyestuffs"),
    ("3814", "38", "Organic composite solvents and thinners, not elsewhere specified"),
    ("3824", "38", "Prepared binders for foundry moulds or cores; chemical products and preparations"),
    ("3825", "38", "Residual products of the chemical or allied industries, not elsewhere specified"),
    # Chapter 39
    ("3901", "39", "Polymers of ethylene, in primary forms"),
    ("3902", "39", "Polymers of propylene or of other olefins, in primary forms"),
    ("3903", "39", "Polymers of styrene, in primary forms"),
    ("3904", "39", "Polymers of vinyl chloride or of other halogenated olefins, in primary forms"),
    ("3907", "39", "Polyacetals, other polyethers and epoxide resins, in primary forms"),
    ("3908", "39", "Polyamides in primary forms"),
    ("3909", "39", "Amino-resins, phenolic resins and polyurethanes, in primary forms"),
    ("3916", "39", "Monofilament of which any cross-sectional dimension exceeds 1 mm, rods, sticks and profile shapes, of plastics"),
    ("3917", "39", "Tubes, pipes and hoses, and fittings therefor, of plastics"),
    ("3919", "39", "Self-adhesive plates, sheets, film, foil, tape, strip and other flat shapes, of plastics"),
    ("3920", "39", "Other plates, sheets, film, foil and strip, of plastics, non-cellular and not reinforced"),
    ("3921", "39", "Other plates, sheets, film, foil and strip, of plastics"),
    ("3923", "39", "Articles for the conveyance or packing of goods, of plastics"),
    ("3924", "39", "Tableware, kitchenware, other household articles and hygienic or toilet articles, of plastics"),
    ("3926", "39", "Other articles of plastics and articles of other materials of headings 39.01 to 39.14"),
    # Chapter 40
    ("4002", "40", "Synthetic rubber and factice derived from oils, in primary forms or in plates, sheets or strip"),
    ("4005", "40", "Compounded rubber, unvulcanised, in primary forms or in plates, sheets or strip"),
    ("4011", "40", "New pneumatic tyres, of rubber"),
    ("4013", "40", "Inner tubes, of rubber"),
    ("4016", "40", "Other articles of vulcanised rubber other than hard rubber"),
    # Chapter 41
    ("4101", "41", "Raw hides and skins of bovine (including buffalo) or equine animals"),
    ("4104", "41", "Tanned or crust hides and skins of bovine (including buffalo) or equine animals"),
    ("4107", "41", "Leather further prepared after tanning or crusting, including parchment-dressed leather"),
    # Chapter 42
    ("4202", "42", "Trunks, suit-cases, vanity-cases, executive-cases, brief-cases, school satchels"),
    ("4203", "42", "Articles of apparel and clothing accessories, of leather or of composition leather"),
    # Chapter 44
    ("4401", "44", "Fuel wood, in logs, in billets, in twigs, in faggots or in similar forms; wood in chips or particles"),
    ("4403", "44", "Wood in the rough, whether or not stripped of bark or sapwood"),
    ("4407", "44", "Wood sawn or chipped lengthwise, sliced or peeled, whether or not planed, sanded or end-jointed"),
    ("4408", "44", "Sheets for veneering (including those obtained by slicing laminated wood)"),
    ("4409", "44", "Wood (including strips and friezes for parquet flooring, not assembled) continuously shaped"),
    ("4410", "44", "Particle board, oriented strand board (OSB) and similar board (for example, waferboard) of wood or other ligneous materials"),
    ("4411", "44", "Fibreboard of wood or other ligneous materials"),
    ("4412", "44", "Plywood, veneered panels and similar laminated wood"),
    ("4418", "44", "Builders' joinery and carpentry of wood, including cellular wood panels, assembled flooring panels, shingles and shakes"),
    # Chapter 48
    ("4801", "48", "Newsprint, in rolls or sheets"),
    ("4802", "48", "Uncoated paper and paperboard, of a kind used for writing, printing or other graphic purposes"),
    ("4804", "48", "Uncoated kraft paper and paperboard, in rolls or sheets"),
    ("4811", "48", "Paper, paperboard, cellulose wadding and webs of cellulose fibres, coated, impregnated, covered, surface-coloured, surface-decorated or printed"),
    ("4819", "48", "Cartons, boxes, cases, bags and other packing containers, of paper, paperboard, cellulose wadding"),
    ("4820", "48", "Registers, account books, notebooks, order books, receipt books, letter pads, memorandum pads, diaries"),
    # Chapter 50-63 (Textiles — selected)
    ("5101", "51", "Wool, not carded or combed"),
    ("5201", "52", "Cotton, not carded or combed"),
    ("5208", "52", "Woven fabrics of cotton, containing 85% or more by weight of cotton, weighing not more than 200 g/m²"),
    ("5209", "52", "Woven fabrics of cotton, containing 85% or more by weight of cotton, weighing more than 200 g/m²"),
    ("5407", "54", "Woven fabrics of synthetic filament yarn"),
    ("5408", "54", "Woven fabrics of artificial filament yarn"),
    ("5512", "55", "Woven fabrics of synthetic staple fibres, containing 85% or more by weight of synthetic staple fibres"),
    ("5515", "55", "Other woven fabrics of synthetic staple fibres"),
    ("6101", "61", "Men's or boys' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets, of knitted or crocheted"),
    ("6102", "61", "Women's or girls' overcoats, car-coats, capes, cloaks, anoraks, of knitted or crocheted"),
    ("6103", "61", "Men's or boys' suits, ensembles, jackets, blazers, trousers, bib and brace overalls, breeches and shorts, knitted or crocheted"),
    ("6104", "61", "Women's or girls' suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers, knitted or crocheted"),
    ("6105", "61", "Men's or boys' shirts, knitted or crocheted"),
    ("6106", "61", "Women's or girls' blouses, shirts and shirt-blouses, knitted or crocheted"),
    ("6109", "61", "T-shirts, singlets and other vests, knitted or crocheted"),
    ("6110", "61", "Jerseys, pullovers, sweatshirts, waistcoats (vests) and similar articles, knitted or crocheted"),
    ("6201", "62", "Men's or boys' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters, wind-jackets"),
    ("6202", "62", "Women's or girls' overcoats, car-coats, capes, cloaks, anoraks (including ski-jackets), wind-cheaters"),
    ("6203", "62", "Men's or boys' suits, ensembles, jackets, blazers, trousers, bib and brace overalls, breeches and shorts"),
    ("6204", "62", "Women's or girls' suits, ensembles, jackets, blazers, dresses, skirts, divided skirts, trousers"),
    ("6205", "62", "Men's or boys' shirts"),
    ("6206", "62", "Women's or girls' blouses, shirts and shirt-blouses"),
    ("6211", "62", "Track suits, ski suits and swimwear; other garments"),
    # Chapter 64
    ("6401", "64", "Waterproof footwear with outer soles and uppers of rubber or of plastics"),
    ("6402", "64", "Other footwear with outer soles and uppers of rubber or plastics"),
    ("6403", "64", "Footwear with outer soles of rubber, plastics, leather or composition leather and uppers of leather"),
    ("6404", "64", "Footwear with outer soles of rubber or plastics and uppers of textile materials"),
    ("6405", "64", "Other footwear"),
    # Chapter 68
    ("6801", "68", "Setts, curbstones and flagstones, of natural stone (except slate)"),
    ("6802", "68", "Worked monumental or building stone and articles thereof"),
    ("6810", "68", "Articles of cement, concrete or artificial stone, whether or not reinforced"),
    ("6811", "68", "Articles of asbestos-cement, of cellulose fibre-cement or the like"),
    # Chapter 69
    ("6901", "69", "Bricks, blocks, tiles and other ceramic goods of siliceous fossil meals"),
    ("6904", "69", "Ceramic building bricks, flooring blocks, support or filler tiles and the like"),
    ("6907", "69", "Ceramic flags and paving, hearth or wall tiles; ceramic mosaic cubes and the like"),
    ("6911", "69", "Tableware, kitchenware, other household articles and toilet articles, of porcelain or china"),
    # Chapter 70
    ("7005", "70", "Float glass and surface ground or polished glass, in sheets"),
    ("7007", "70", "Safety glass, consisting of toughened (tempered) or laminated glass"),
    ("7013", "70", "Glassware of a kind used for table, kitchen, toilet, office, indoor decoration or similar purposes"),
    # Chapter 71
    ("7102", "71", "Diamonds, whether or not worked, but not mounted or set"),
    ("7108", "71", "Gold (including gold plated with platinum), unwrought or in semi-manufactured forms"),
    ("7113", "71", "Articles of jewellery and parts thereof, of precious metal or of metal clad with precious metal"),
    ("7116", "71", "Articles of natural or cultured pearls, precious or semi-precious stones"),
    # Chapter 72
    ("7201", "72", "Pig iron and spiegeleisen in pigs, blocks or other primary forms"),
    ("7204", "72", "Ferrous waste and scrap; remelting scrap ingots of iron or steel"),
    ("7207", "72", "Semi-finished products of iron or non-alloy steel"),
    ("7208", "72", "Flat-rolled products of iron or non-alloy steel, of a width of 600 mm or more, hot-rolled"),
    ("7209", "72", "Flat-rolled products of iron or non-alloy steel, of a width of 600 mm or more, cold-rolled"),
    ("7210", "72", "Flat-rolled products of iron or non-alloy steel, of a width of 600 mm or more, clad, plated or coated"),
    ("7213", "72", "Bars and rods, hot-rolled, in irregularly wound coils, of iron or non-alloy steel"),
    ("7214", "72", "Other bars and rods of iron or non-alloy steel, not further worked than forged, hot-rolled, hot-drawn"),
    ("7216", "72", "Angles, shapes and sections of iron or non-alloy steel"),
    ("7219", "72", "Flat-rolled products of stainless steel, of a width of 600 mm or more"),
    ("7225", "72", "Flat-rolled products of other alloy steel, of a width of 600 mm or more"),
    # Chapter 73
    ("7301", "73", "Sheet piling of iron or steel, whether or not drilled, punched or made from assembled elements"),
    ("7304", "73", "Tubes, pipes and hollow profiles, seamless, of iron (other than cast iron) or steel"),
    ("7305", "73", "Other tubes and pipes (for example, welded, riveted or similarly closed)"),
    ("7306", "73", "Other tubes, pipes and hollow profiles (for example, open seam or welded, riveted or similarly closed)"),
    ("7308", "73", "Structures (excluding prefabricated buildings of heading 94.06) and parts of structures"),
    ("7314", "73", "Cloth (including endless bands), grill, netting and fencing, of iron or steel wire"),
    ("7317", "73", "Nails, tacks, drawing pins, corrugated nails, staples (other than those of heading 83.05)"),
    ("7318", "73", "Screws, bolts, nuts, coach screws, screw hooks, rivets, cotters, cotter-pins, washers"),
    ("7320", "73", "Springs and leaves for springs, of iron or steel"),
    ("7323", "73", "Table, kitchen or other household articles and parts thereof, of iron or steel"),
    ("7326", "73", "Other articles of iron or steel"),
    # Chapter 74
    ("7401", "74", "Copper mattes; cement copper (precipitated copper)"),
    ("7403", "74", "Refined copper and copper alloys, unwrought"),
    ("7408", "74", "Copper wire"),
    ("7411", "74", "Copper tubes and pipes"),
    # Chapter 76
    ("7601", "76", "Unwrought aluminium"),
    ("7604", "76", "Aluminium bars, rods and profiles"),
    ("7606", "76", "Aluminium plates, sheets and strip, of a thickness exceeding 0.2 mm"),
    ("7608", "76", "Aluminium tubes and pipes"),
    ("7610", "76", "Aluminium structures (excluding prefabricated buildings of heading 94.06) and parts of structures"),
    ("7612", "76", "Aluminium casks, drums, cans, boxes and similar containers"),
    ("7616", "76", "Other articles of aluminium"),
    # Chapter 82
    ("8201", "82", "Hand tools of the following kinds: spades, shovels, mattocks, picks, hoes, forks and rakes"),
    ("8203", "82", "Files, rasps, pliers (including cutting pliers), pincers, tweezers, metal cutting shears"),
    ("8204", "82", "Hand-operated spanners and wrenches (including torque meter wrenches)"),
    ("8205", "82", "Hand tools (including glaziers' diamonds), not elsewhere specified or included"),
    ("8207", "82", "Interchangeable tools for hand tools, whether or not power-operated"),
    ("8208", "82", "Knives and cutting blades, for machines or for mechanical appliances"),
    # Chapter 83
    ("8301", "83", "Padlocks and locks (key, combination or electrically operated), of base metal"),
    ("8302", "83", "Base metal mountings, fittings and similar articles suitable for furniture, doors, staircases, windows, blinds, coachwork"),
    ("8306", "83", "Bells, gongs and the like, non-electric, of base metal; statuettes and other ornaments of base metal"),
    ("8308", "83", "Clasps, frames with clasps, buckles, buckle-clasps, hooks, eyes, eyelets and the like, of base metal"),
    # Chapter 84 — Machinery (key headings)
    ("8401", "84", "Nuclear reactors; fuel elements (cartridges), non-irradiated, for nuclear reactors; machinery and apparatus for isotope-separation"),
    ("8402", "84", "Steam or other vapour generating boilers (other than central heating hot water boilers capable also of producing low pressure steam)"),
    ("8403", "84", "Central heating boilers other than those of heading 84.02"),
    ("8404", "84", "Auxiliary plant for use with boilers of heading 84.02 or 84.03"),
    ("8405", "84", "Producer gas or water gas generators, with or without their purifiers; acetylene gas generators"),
    ("8406", "84", "Steam turbines and other vapour turbines"),
    ("8407", "84", "Spark-ignition reciprocating or rotary internal combustion piston engines"),
    ("8408", "84", "Compression-ignition internal combustion piston engines (diesel or semi-diesel engines)"),
    ("8409", "84", "Parts suitable for use solely or principally with the engines of heading 84.07 or 84.08"),
    ("8410", "84", "Hydraulic turbines, water wheels, and regulators therefor"),
    ("8411", "84", "Turbojets, turbopropellers and other gas turbines"),
    ("8412", "84", "Other engines and motors"),
    ("8413", "84", "Pumps for liquids, whether or not fitted with a measuring device; liquid elevators"),
    ("8414", "84", "Air or vacuum pumps, air or other gas compressors and fans; ventilating or recycling hoods incorporating a fan"),
    ("8415", "84", "Air conditioning machines, comprising a motor-driven fan and elements for changing the temperature and humidity"),
    ("8416", "84", "Furnace burners for liquid fuel, for pulverised solid fuel or for gas; mechanical stokers"),
    ("8417", "84", "Industrial or laboratory furnaces and ovens, including incinerators, non-electric"),
    ("8418", "84", "Refrigerators, freezers and other refrigerating or freezing equipment, electric or other; heat pumps"),
    ("8419", "84", "Machinery, plant or laboratory equipment, whether or not electrically heated, for the treatment of materials by a process involving a change of temperature"),
    ("8420", "84", "Calendering or other rolling machines, other than for metals or glass, and cylinders therefor"),
    ("8421", "84", "Centrifuges, including centrifugal dryers; filtering or purifying machinery and apparatus, for liquids or gases"),
    ("8422", "84", "Dish washing machines; machinery for cleaning or drying bottles or other containers; machinery for filling, closing, sealing or labelling bottles, cans, boxes, bags"),
    ("8423", "84", "Weighing machinery (excluding balances of a sensitivity of 5 cg or better)"),
    ("8424", "84", "Mechanical appliances (whether or not hand-operated) for projecting, dispersing or spraying liquids or powders"),
    ("8425", "84", "Pulley tackle and hoists other than skip hoists; winches and capstans; jacks"),
    ("8426", "84", "Ships' derricks; cranes, including cable cranes; mobile lifting frames, straddle carriers and works trucks fitted with a crane"),
    ("8427", "84", "Fork-lift trucks; other works trucks fitted with lifting or handling equipment"),
    ("8428", "84", "Other lifting, handling, loading or unloading machinery"),
    ("8429", "84", "Self-propelled bulldozers, angledozers, graders, levellers, scrapers, mechanical shovels, excavators"),
    ("8430", "84", "Other moving, grading, levelling, scraping, excavating, tamping, compacting, extracting or boring machinery"),
    ("8431", "84", "Parts suitable for use solely or principally with the machinery of headings 84.25 to 84.30"),
    ("8432", "84", "Agricultural, horticultural or forestry machinery for soil preparation or cultivation"),
    ("8433", "84", "Harvesting or threshing machinery, including straw or fodder balers"),
    ("8434", "84", "Milking machines and dairy machinery"),
    ("8435", "84", "Presses, crushers and similar machinery used in the manufacture of wine, cider, fruit juices or similar beverages"),
    ("8436", "84", "Other agricultural, horticultural, forestry, poultry-keeping or bee-keeping machinery"),
    ("8437", "84", "Machines for cleaning, sorting or grading seed, grain or dried leguminous vegetables"),
    ("8438", "84", "Machinery, not specified or included elsewhere in this chapter, for the industrial preparation or manufacture of food or drink"),
    ("8439", "84", "Machinery for making pulp of fibrous cellulosic material or for making or finishing paper or paperboard"),
    ("8440", "84", "Bookbinding machinery, including book-sewing machines"),
    ("8441", "84", "Other machinery for making up paper pulp, paper or paperboard, including cutting machines of all kinds"),
    ("8443", "84", "Printing machinery used for printing by means of plates, cylinders and other printing components of heading 84.42"),
    ("8444", "84", "Machines for extruding, drawing, texturing or cutting man-made textile materials"),
    ("8445", "84", "Machines for preparing textile fibres; spinning, doubling or twisting machines"),
    ("8450", "84", "Household or laundry-type washing machines, including machines which both wash and dry"),
    ("8451", "84", "Machinery (other than machines of heading 84.50) for washing, cleaning, wringing, drying, ironing, pressing, bleaching, dyeing, dressing, finishing, coating or impregnating textile yarns, fabrics or made up textile articles"),
    ("8452", "84", "Sewing machines, other than book-sewing machines of heading 84.40; furniture, bases and covers specially designed for sewing machines; sewing machine needles"),
    ("8453", "84", "Machinery for preparing, tanning or working hides, skins or leather or for making or repairing footwear or other articles of hides, skins or leather"),
    ("8454", "84", "Converters, ladles, ingot moulds and casting machines, of a kind used in metallurgy or in metal foundries"),
    ("8455", "84", "Metal-rolling mills and rolls therefor"),
    ("8456", "84", "Machine-tools for working any material by removal of material, by laser or other light or photon beam, ultrasonic, electro-discharge, electro-chemical, electron beam, ionic-beam or plasma arc processes"),
    ("8457", "84", "Machining centres, unit construction machines (single station) and multi-station transfer machines, for working metal"),
    ("8458", "84", "Lathes (including turning centres) for removing metal"),
    ("8459", "84", "Machine-tools (including way-type unit head machines) for drilling, boring, milling, threading or tapping by removing metal"),
    ("8460", "84", "Machine-tools for deburring, sharpening, grinding, honing, lapping, polishing or otherwise finishing metal"),
    ("8461", "84", "Machine-tools for planing, shaping, slotting, broaching, gear cutting, gear grinding or gear finishing, sawing, cutting-off and other machine-tools working by removing metal"),
    ("8462", "84", "Machine-tools (including presses) for working metal by forging, hammering or die-stamping"),
    ("8463", "84", "Other machine-tools for working metal or cermets, without removing material"),
    ("8464", "84", "Machine-tools for working stone, ceramics, concrete, asbestos-cement or like mineral materials or for cold working glass"),
    ("8465", "84", "Machine-tools (including machines for nailing, stapling, glueing or otherwise assembling) for working wood, cork, bone, hard rubber, hard plastics or similar hard materials"),
    ("8466", "84", "Parts and accessories suitable for use solely or principally with the machines of headings 84.56 to 84.65"),
    ("8467", "84", "Tools for working in the hand, pneumatic, hydraulic or with self-contained electric or non-electric motor"),
    ("8468", "84", "Machinery and apparatus for soldering, brazing or welding, whether or not capable of cutting"),
    ("8469", "84", "Typewriters other than printers of heading 84.43; word-processing machines"),
    ("8470", "84", "Calculating machines and pocket-size data recording, reproducing and displaying machines with calculating functions"),
    ("8471", "84", "Automatic data processing machines and units thereof; magnetic or optical readers, machines for transcribing data on to data media in coded form and machines for processing such data"),
    ("8472", "84", "Other office machines (for example, hectograph or stencil duplicating machines, addressing machines, automatic banknote dispensers, coin-sorting machines)"),
    ("8473", "84", "Parts and accessories (other than covers, carrying cases and the like) suitable for use solely or principally with machines of headings 84.69 to 84.72"),
    ("8474", "84", "Machinery for sorting, screening, separating, washing, crushing, grinding, mixing or kneading earth, stone, ores or other mineral substances"),
    ("8475", "84", "Machines for assembling electric or electronic lamps, tubes or valves or flashbulbs, in glass envelopes"),
    ("8476", "84", "Automatic goods-vending machines (for example, postage stamp, cigarette, food or beverage machines)"),
    ("8477", "84", "Machinery for working rubber or plastics or for the manufacture of products from these materials"),
    ("8478", "84", "Machinery for preparing or making up tobacco, not specified or included elsewhere in this chapter"),
    ("8479", "84", "Machines and mechanical appliances having individual functions, not specified or included elsewhere in this chapter"),
    ("8480", "84", "Moulding boxes for metal foundry; mould bases; moulding patterns; moulds for metal, metal carbides, glass, mineral materials, rubber or plastics"),
    ("8481", "84", "Taps, cocks, valves and similar appliances for pipes, boiler shells, tanks, vats or the like"),
    ("8482", "84", "Ball or roller bearings"),
    ("8483", "84", "Transmission shafts (including cam shafts and crank shafts) and cranks; bearing housings and plain shaft bearings"),
    ("8484", "84", "Gaskets and similar joints of metal sheeting combined with other material or of two or more layers of metal"),
    ("8486", "84", "Machines and apparatus of a kind used solely or principally for the manufacture of semiconductor boules or wafers, semiconductor devices, electronic integrated circuits or flat panel displays"),
    ("8487", "84", "Machinery parts, not containing electrical connectors, insulators, coils, contacts or other electrical features, not specified or included elsewhere in this chapter"),
    # Chapter 85 — Electrical machinery
    ("8501", "85", "Electric motors and generators (excluding generating sets)"),
    ("8502", "85", "Electric generating sets and rotary converters"),
    ("8503", "85", "Parts suitable for use solely or principally with the machines of heading 85.01 or 85.02"),
    ("8504", "85", "Electrical transformers, static converters (for example, rectifiers) and inductors"),
    ("8505", "85", "Electromagnets; permanent magnets and articles intended to become permanent magnets after magnetisation"),
    ("8506", "85", "Primary cells and primary batteries"),
    ("8507", "85", "Electric accumulators, including separators therefor, whether or not rectangular (including square)"),
    ("8508", "85", "Vacuum cleaners"),
    ("8509", "85", "Electro-mechanical domestic appliances, with self-contained electric motor, other than vacuum cleaners of heading 85.08"),
    ("8510", "85", "Shavers, hair clippers and hair-removing appliances, with self-contained electric motor"),
    ("8511", "85", "Electrical ignition or starting equipment of a kind used for spark-ignition or compression-ignition internal combustion engines"),
    ("8512", "85", "Electrical lighting or signalling equipment (excluding articles of heading 85.39), windscreen wipers, defrosters and demisters"),
    ("8513", "85", "Portable electric lamps designed to function by their own source of energy"),
    ("8514", "85", "Industrial or laboratory electric furnaces and ovens (including those functioning by induction or dielectric loss)"),
    ("8515", "85", "Electric (including electrically heated gas), laser or other light or photon beam, ultrasonic, electron beam, magnetic pulse or plasma arc soldering, brazing or welding machines and apparatus"),
    ("8516", "85", "Electric instantaneous or storage water heaters and immersion heaters; electric space heating apparatus and soil heating apparatus"),
    ("8517", "85", "Telephone sets, including telephones for cellular networks or for other wireless networks; other apparatus for the transmission or reception of voice, images or other data"),
    ("8518", "85", "Microphones and stands therefor; loudspeakers, whether or not mounted in their enclosures; headphones and earphones"),
    ("8519", "85", "Sound recording or reproducing apparatus"),
    ("8521", "85", "Video recording or reproducing apparatus, whether or not incorporating a video tuner"),
    ("8522", "85", "Parts and accessories suitable for use solely or principally with the apparatus of headings 85.19 to 85.21"),
    ("8523", "85", "Discs, tapes, solid-state non-volatile storage devices, smart cards and other media for the recording of sound or of other phenomena"),
    ("8524", "85", "Flat panel display modules, whether or not incorporating touch-sensitive screens"),
    ("8525", "85", "Transmission apparatus for radio-broadcasting or television, whether or not incorporating reception apparatus or sound recording or reproducing apparatus"),
    ("8526", "85", "Radar apparatus, radio navigational aid apparatus and radio remote control apparatus"),
    ("8527", "85", "Reception apparatus for radio-broadcasting, whether or not combined in the same housing with sound recording or reproducing apparatus or a clock"),
    ("8528", "85", "Monitors and projectors, not incorporating television reception apparatus; reception apparatus for television, whether or not incorporating radio-broadcast receivers or sound or video recording or reproducing apparatus"),
    ("8529", "85", "Parts suitable for use solely or principally with the apparatus of headings 85.25 to 85.28"),
    ("8530", "85", "Electrical signalling, safety or traffic control equipment for railways, tramways, roads, inland waterways, parking facilities, port installations or airfields"),
    ("8531", "85", "Electric sound or visual signalling apparatus (for example, bells, sirens, indicator panels, burglar or fire alarms)"),
    ("8532", "85", "Electrical capacitors, fixed, variable or adjustable (pre-set)"),
    ("8533", "85", "Electrical resistors (including rheostats and potentiometers), other than heating resistors"),
    ("8534", "85", "Printed circuits"),
    ("8535", "85", "Electrical apparatus for switching or protecting electrical circuits, or for making connections to or in electrical circuits (for example, switches, fuses, lightning arresters), for a voltage exceeding 1,000 volts"),
    ("8536", "85", "Electrical apparatus for switching or protecting electrical circuits, or for making connections to or in electrical circuits, for a voltage not exceeding 1,000 volts"),
    ("8537", "85", "Boards, panels, consoles, desks, cabinets and other bases, equipped with two or more apparatus of heading 85.35 or 85.36"),
    ("8538", "85", "Parts suitable for use solely or principally with the apparatus of heading 85.35, 85.36 or 85.37"),
    ("8539", "85", "Electric filament or discharge lamps, including sealed beam lamp units and ultra-violet or infra-red lamps; arc-lamps; light-emitting diode (LED) lamps"),
    ("8540", "85", "Thermionic, cold cathode or photo-cathode valves and tubes (for example, vacuum or vapour or gas filled valves and tubes, mercury arc rectifying valves and tubes, cathode-ray tubes, television camera tubes)"),
    ("8541", "85", "Semiconductor devices (for example, diodes, transistors, semiconductor-based transducers)"),
    ("8542", "85", "Electronic integrated circuits"),
    ("8543", "85", "Electrical machines and apparatus, having individual functions, not specified or included elsewhere in this chapter"),
    ("8544", "85", "Insulated (including enamelled or anodised) wire, cable (including coaxial cable) and other insulated electric conductors"),
    ("8545", "85", "Carbon electrodes, carbon brushes, lamp carbons, battery carbons and other articles of graphite or other carbon, with or without metal, of a kind used for electrical purposes"),
    ("8546", "85", "Electrical insulators of any material"),
    ("8547", "85", "Insulating fittings for electrical machines, appliances or equipment, being fittings wholly of insulating material"),
    ("8548", "85", "Waste and scrap of primary cells, primary batteries and electric accumulators; spent primary cells, spent primary batteries and spent electric accumulators"),
    # Chapter 86
    ("8601", "86", "Rail locomotives powered from an external source of electricity or by electric accumulators"),
    ("8602", "86", "Other rail locomotives; locomotive tenders"),
    ("8603", "86", "Self-propelled railway or tramway coaches, vans and trucks, other than those of heading 86.04"),
    ("8607", "86", "Parts of railway or tramway locomotives or rolling-stock"),
    # Chapter 87 — Vehicles
    ("8701", "87", "Tractors (other than tractors of heading 87.09)"),
    ("8702", "87", "Motor vehicles for the transport of 10 or more persons, including the driver"),
    ("8703", "87", "Motor cars and other motor vehicles principally designed for the transport of persons"),
    ("8704", "87", "Motor vehicles for the transport of goods"),
    ("8705", "87", "Special purpose motor vehicles, other than those principally designed for the transport of persons or goods"),
    ("8706", "87", "Chassis fitted with engines, for the motor vehicles of headings 87.01 to 87.05"),
    ("8707", "87", "Bodies (including cabs), for the motor vehicles of headings 87.01 to 87.05"),
    ("8708", "87", "Parts and accessories of the motor vehicles of headings 87.01 to 87.05"),
    ("8709", "87", "Works trucks, self-propelled, not fitted with lifting or handling equipment, of the type used in factories, warehouses, dock areas or airports"),
    ("8711", "87", "Motorcycles (including mopeds) and cycles fitted with an auxiliary motor, with or without side-cars; side-cars"),
    ("8712", "87", "Bicycles and other cycles (including delivery tricycles), not motorised"),
    ("8713", "87", "Invalid carriages, whether or not motorised or otherwise mechanically propelled"),
    ("8714", "87", "Parts and accessories of vehicles of headings 87.11 to 87.13"),
    ("8715", "87", "Baby carriages (including strollers) and parts thereof"),
    ("8716", "87", "Trailers and semi-trailers; other vehicles, not mechanically propelled; parts thereof"),
    # Chapter 88
    ("8801", "88", "Balloons and dirigibles; gliders, hang gliders and other non-powered aircraft"),
    ("8802", "88", "Other aircraft (for example, helicopters, aeroplanes); spacecraft (including satellites) and suborbital and spacecraft launch vehicles"),
    ("8803", "88", "Parts of goods of heading 88.01 or 88.02"),
    # Chapter 89
    ("8901", "89", "Cruise ships, excursion boats, ferry-boats, cargo ships, barges and similar vessels for the transport of persons or goods"),
    ("8902", "89", "Fishing vessels; factory ships and other vessels for processing or preserving fishery products"),
    ("8903", "89", "Yachts and other vessels for pleasure or sports; rowing boats and canoes"),
    ("8904", "89", "Tugs and pusher craft"),
    ("8905", "89", "Light-vessels, fire-floats, dredgers, floating cranes, and other vessels the navigability of which is subsidiary to their main function"),
    # Chapter 90
    ("9001", "90", "Optical fibres and optical fibre bundles; optical fibre cables other than those of heading 85.44"),
    ("9002", "90", "Lenses, prisms, mirrors and other optical elements, of any material, mounted, being parts of or fittings for instruments or apparatus"),
    ("9003", "90", "Frames and mountings for spectacles, goggles or the like, and parts thereof"),
    ("9004", "90", "Spectacles, goggles and the like, corrective, protective or other"),
    ("9006", "90", "Photographic (other than cinematographic) cameras; photographic flashlight apparatus and flashbulbs"),
    ("9007", "90", "Cinematographic cameras and projectors, whether or not incorporating sound recording or reproducing apparatus"),
    ("9008", "90", "Image projectors, other than cinematographic; photographic (other than cinematographic) enlargers and reducers"),
    ("9010", "90", "Apparatus and equipment for photographic (including cinematographic) laboratories"),
    ("9013", "90", "Liquid crystal devices not constituting articles provided for more specifically in other headings; lasers, other than laser diodes; other optical appliances and instruments"),
    ("9014", "90", "Direction finding compasses; other navigational instruments and appliances"),
    ("9015", "90", "Surveying (including photogrammetrical surveying), hydrographic, oceanographic, hydrological, meteorological or geophysical instruments and appliances, excluding compasses"),
    ("9016", "90", "Balances of a sensitivity of 5 cg or better, with or without weights"),
    ("9017", "90", "Drawing, marking-out or mathematical calculating instruments (for example, drafting machines, pantographs, protractors, drawing sets, slide rules, disc calculators)"),
    ("9018", "90", "Instruments and appliances used in medical, surgical, dental or veterinary sciences, including scintigraphic apparatus, other electro-medical apparatus and sight-testing instruments"),
    ("9019", "90", "Mechano-therapy appliances; massage apparatus; psychological aptitude-testing apparatus; ozone therapy, oxygen therapy, aerosol therapy, artificial respiration or other therapeutic respiration apparatus"),
    ("9020", "90", "Other breathing appliances and gas masks, excluding protective masks having neither mechanical parts nor replaceable filters"),
    ("9021", "90", "Orthopaedic appliances, including crutches, surgical belts and trusses; splints and other fracture appliances; artificial parts of the body; hearing aids and other appliances which are worn or carried, or implanted in the body, to compensate for a defect or disability"),
    ("9022", "90", "Apparatus based on the use of X-rays or of alpha, beta, gamma or other ionising radiations"),
    ("9025", "90", "Hydrometers and similar floating instruments, thermometers, pyrometers, barometers, hygrometers and psychrometers, recording or not"),
    ("9026", "90", "Instruments and apparatus for measuring or checking the flow, level, pressure or other variables of liquids or gases"),
    ("9027", "90", "Instruments and apparatus for physical or chemical analysis"),
    ("9028", "90", "Gas, liquid or electricity supply or production meters, including calibrating meters therefor"),
    ("9029", "90", "Revolution counters, production counters, taximeters, milometers, pedometers and the like"),
    ("9030", "90", "Oscilloscopes, spectrum analysers and other instruments and apparatus for measuring or checking electrical quantities"),
    ("9031", "90", "Measuring or checking instruments, appliances and machines, not specified or included elsewhere in this chapter"),
    ("9032", "90", "Automatic regulating or controlling instruments and apparatus"),
    ("9033", "90", "Parts and accessories (not specified or included elsewhere in this chapter) for machines, appliances, instruments or apparatus of chapter 90"),
    # Chapter 91
    ("9101", "91", "Wrist-watches, pocket-watches and other watches, including stop-watches, with case of precious metal or of metal clad with precious metal"),
    ("9102", "91", "Wrist-watches, pocket-watches and other watches, including stop-watches, other than those of heading 91.01"),
    ("9103", "91", "Clocks with watch movements, excluding clocks of heading 91.04"),
    ("9105", "91", "Other clocks"),
    ("9108", "91", "Watch movements, complete and assembled"),
    # Chapter 94
    ("9401", "94", "Seats (other than those of heading 94.02), whether or not convertible into beds, and parts thereof"),
    ("9402", "94", "Medical, surgical, dental or veterinary furniture (for example, operating tables, examination tables, hospital beds with mechanical fittings, dentists' chairs)"),
    ("9403", "94", "Other furniture and parts thereof"),
    ("9404", "94", "Mattress supports; articles of bedding and similar furnishing (for example, mattresses, quilts, eiderdowns, cushions, pouffes and pillows) fitted with springs"),
    ("9405", "94", "Luminaires and lighting fittings including searchlights and spotlights and parts thereof, not elsewhere specified or included; illuminated signs, illuminated name-plates and the like"),
    ("9406", "94", "Prefabricated buildings"),
    # Chapter 95
    ("9501", "95", "Wheeled toys designed to be ridden by children (for example, tricycles, scooters, pedal cars); dolls' carriages"),
    ("9503", "95", "Tricycles, scooters, pedal cars and similar wheeled toys; dolls' carriages; dolls; other toys; reduced-size (scale) models and similar recreational models, working or not; puzzles of all kinds"),
    ("9504", "95", "Video game consoles and machines, articles for funfair, table or parlour games"),
    ("9506", "95", "Articles and equipment for general physical exercise, gymnastics, athletics, other sports or outdoor games; swimming pools and paddling pools"),
    ("9507", "95", "Fishing rods, fish-hooks and other line fishing tackle; fish landing nets, butterfly nets and similar nets; decoy birds and similar hunting or shooting requisites"),
    # Chapter 96
    ("9601", "96", "Worked ivory, bone, tortoise-shell, horn, antlers, coral, mother-of-pearl and other animal carving material, and articles of these materials"),
    ("9603", "96", "Brooms, brushes (including brushes constituting parts of machines, appliances or vehicles), hand-operated mechanical floor sweepers"),
    ("9606", "96", "Buttons, press-fasteners, snap-fasteners and press-studs, button moulds and other parts of these articles; button blanks"),
    ("9607", "96", "Slide fasteners and parts thereof"),
    ("9608", "96", "Ball point pens; felt tipped and other porous-tipped pens and markers; fountain pens, stylograph pens and other pens; duplicating stylos"),
    ("9613", "96", "Cigarette lighters and other lighters, whether or not mechanical or electrical, and parts thereof other than flints and wicks"),
    ("9614", "96", "Smoking pipes (including pipe bowls) and cigar or cigarette holders, and parts thereof"),
    ("9615", "96", "Combs, hair-slides and the like; hairpins, curling pins, curling grips, hair-curlers and the like"),
    # Chapter 97
    ("9701", "97", "Paintings, drawings and pastels, executed entirely by hand, other than drawings of heading 49.06 and other than hand-painted or hand-decorated manufactured articles"),
    ("9702", "97", "Original engravings, prints and lithographs"),
    ("9703", "97", "Original sculptures and statuary, in any material"),
    ("9704", "97", "Postage or revenue stamps, stamp-postmarks, first-day covers, postal stationery (stamped paper), and the like, used or unused, other than those of heading 49.07"),
    ("9705", "97", "Collections and collectors' pieces of zoological, botanical, mineralogical, anatomical, historical, archaeological, palaeontological, ethnographic or numismatic interest"),
    ("9706", "97", "Antiques of an age exceeding one hundred years"),
]
